# Generated by Django 4.2.10 on 2024-03-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_url', models.URLField(max_length=1024)),
                ('detail_title', models.CharField(max_length=1024)),
                ('detail_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SummaryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_url', models.URLField(max_length=1024)),
                ('article_title', models.CharField(max_length=1024)),
                ('article_link', models.URLField(max_length=1024)),
                ('article_summary', models.TextField()),
                ('press', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('keywords', models.TextField()),
            ],
        ),
    ]
